import { TemplateDefinition } from '@/lib/types';

/**
 * HERO OVERLAY — 1 foto grande con degradado oscuro abajo y datos superpuestos.
 * Ideal para posts de impacto con una foto protagonista.
 */
export const heroOverlay: TemplateDefinition = {
  id: 'hero-overlay',
  version: '1.0.0',
  name: 'Hero con Overlay',
  description: '1 foto grande con degradado y datos superpuestos',
  category: 'hero',
  imageCount: 1,
  supportedFormats: ['1080x1080', '1080x1350', '1080x1920'],
  safeArea: { top: 60, bottom: 60, left: 40, right: 40 },
  tags: ['hero', 'impacto', '1-foto'],
  slides: {
    '1080x1080': [
      {
        id: 'main',
        layers: [
          // Background image
          {
            type: 'image',
            id: 'bg-image',
            imageIndex: 0,
            rect: { x: 0, y: 0, width: 1080, height: 1080 },
            fit: 'cover',
            zIndex: 0,
          },
          // Gradient overlay (bottom)
          {
            type: 'shape',
            id: 'gradient-bottom',
            shape: 'gradient-overlay',
            rect: { x: 0, y: 440, width: 1080, height: 640 },
            gradient: {
              type: 'linear',
              direction: 'to-bottom',
              stops: [
                { offset: 0, color: '#000000', opacity: 0 },
                { offset: 0.4, color: '#000000', opacity: 0.6 },
                { offset: 1, color: '#000000', opacity: 0.85 },
              ],
            },
            zIndex: 1,
          },
          // Operation badge (VENTA/ALQUILER)
          {
            type: 'shape',
            id: 'operation-badge-bg',
            shape: 'rect',
            rect: { x: 60, y: 60, width: 200, height: 48 },
            fill: 'brand.primary',
            borderRadius: 8,
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'operation-text',
            field: 'custom',
            rect: { x: 60, y: 60, width: 200, height: 48 },
            defaultText: 'EN VENTA',
            style: {
              fontFamily: 'Inter',
              color: '#FFFFFF',
              fontSize: 22,
              fontWeight: 'bold',
              textAlign: 'center',
              textTransform: 'uppercase',
              letterSpacing: 2,
            },
            zIndex: 3,
          },
          // Title
          {
            type: 'text',
            id: 'title',
            field: 'title',
            rect: { x: 60, y: 720, width: 960, height: 80 },
            style: {
              fontFamily: 'Inter',
              color: '#FFFFFF',
              fontSize: 42,
              fontWeight: 'bold',
              textAlign: 'left',
              lineHeight: 1.1,
              maxLines: 2,
            },
            zIndex: 2,
          },
          // Price
          {
            type: 'text',
            id: 'price',
            field: 'price',
            rect: { x: 60, y: 810, width: 960, height: 60 },
            style: {
              fontFamily: 'Inter',
              color: 'brand.secondary',
              fontSize: 48,
              fontWeight: 'black',
              textAlign: 'left',
            },
            zIndex: 2,
          },
          // Location
          {
            type: 'text',
            id: 'location',
            field: 'location',
            rect: { x: 60, y: 880, width: 600, height: 40 },
            style: {
              fontFamily: 'Inter',
              color: '#CCCCCC',
              fontSize: 26,
              fontWeight: 'normal',
              textAlign: 'left',
            },
            zIndex: 2,
          },
          // Features
          {
            type: 'text',
            id: 'features',
            field: 'features',
            rect: { x: 60, y: 930, width: 700, height: 40 },
            style: {
              fontFamily: 'Inter',
              color: '#AAAAAA',
              fontSize: 22,
              fontWeight: 'normal',
              textAlign: 'left',
              maxLines: 1,
            },
            zIndex: 2,
          },
          // Logo
          {
            type: 'logo',
            id: 'logo',
            rect: { x: 860, y: 920, width: 160, height: 100 },
            fit: 'contain',
            zIndex: 2,
          },
          // CTA
          {
            type: 'text',
            id: 'cta',
            field: 'cta',
            rect: { x: 60, y: 990, width: 700, height: 36 },
            style: {
              fontFamily: 'Inter',
              color: 'brand.secondary',
              fontSize: 20,
              fontWeight: 'bold',
              textAlign: 'left',
            },
            zIndex: 2,
          },
        ],
      },
    ],
    '1080x1350': [
      {
        id: 'main',
        layers: [
          {
            type: 'image',
            id: 'bg-image',
            imageIndex: 0,
            rect: { x: 0, y: 0, width: 1080, height: 1350 },
            fit: 'cover',
            zIndex: 0,
          },
          {
            type: 'shape',
            id: 'gradient-bottom',
            shape: 'gradient-overlay',
            rect: { x: 0, y: 650, width: 1080, height: 700 },
            gradient: {
              type: 'linear',
              direction: 'to-bottom',
              stops: [
                { offset: 0, color: '#000000', opacity: 0 },
                { offset: 0.4, color: '#000000', opacity: 0.6 },
                { offset: 1, color: '#000000', opacity: 0.85 },
              ],
            },
            zIndex: 1,
          },
          {
            type: 'shape',
            id: 'operation-badge-bg',
            shape: 'rect',
            rect: { x: 60, y: 60, width: 200, height: 48 },
            fill: 'brand.primary',
            borderRadius: 8,
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'operation-text',
            field: 'custom',
            rect: { x: 60, y: 60, width: 200, height: 48 },
            defaultText: 'EN VENTA',
            style: {
              fontFamily: 'Inter',
              color: '#FFFFFF',
              fontSize: 22,
              fontWeight: 'bold',
              textAlign: 'center',
              textTransform: 'uppercase',
              letterSpacing: 2,
            },
            zIndex: 3,
          },
          {
            type: 'text',
            id: 'title',
            field: 'title',
            rect: { x: 60, y: 980, width: 960, height: 80 },
            style: {
              fontFamily: 'Inter',
              color: '#FFFFFF',
              fontSize: 44,
              fontWeight: 'bold',
              textAlign: 'left',
              lineHeight: 1.1,
              maxLines: 2,
            },
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'price',
            field: 'price',
            rect: { x: 60, y: 1070, width: 960, height: 60 },
            style: {
              fontFamily: 'Inter',
              color: 'brand.secondary',
              fontSize: 52,
              fontWeight: 'black',
              textAlign: 'left',
            },
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'location',
            field: 'location',
            rect: { x: 60, y: 1140, width: 600, height: 40 },
            style: {
              fontFamily: 'Inter',
              color: '#CCCCCC',
              fontSize: 28,
              fontWeight: 'normal',
              textAlign: 'left',
            },
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'features',
            field: 'features',
            rect: { x: 60, y: 1190, width: 700, height: 40 },
            style: {
              fontFamily: 'Inter',
              color: '#AAAAAA',
              fontSize: 24,
              fontWeight: 'normal',
              textAlign: 'left',
              maxLines: 1,
            },
            zIndex: 2,
          },
          {
            type: 'logo',
            id: 'logo',
            rect: { x: 860, y: 1190, width: 160, height: 100 },
            fit: 'contain',
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'cta',
            field: 'cta',
            rect: { x: 60, y: 1260, width: 700, height: 36 },
            style: {
              fontFamily: 'Inter',
              color: 'brand.secondary',
              fontSize: 22,
              fontWeight: 'bold',
              textAlign: 'left',
            },
            zIndex: 2,
          },
        ],
      },
    ],
    '1080x1920': [
      {
        id: 'main',
        layers: [
          {
            type: 'image',
            id: 'bg-image',
            imageIndex: 0,
            rect: { x: 0, y: 0, width: 1080, height: 1920 },
            fit: 'cover',
            zIndex: 0,
          },
          {
            type: 'shape',
            id: 'gradient-bottom',
            shape: 'gradient-overlay',
            rect: { x: 0, y: 1200, width: 1080, height: 720 },
            gradient: {
              type: 'linear',
              direction: 'to-bottom',
              stops: [
                { offset: 0, color: '#000000', opacity: 0 },
                { offset: 0.35, color: '#000000', opacity: 0.65 },
                { offset: 1, color: '#000000', opacity: 0.9 },
              ],
            },
            zIndex: 1,
          },
          {
            type: 'shape',
            id: 'operation-badge-bg',
            shape: 'rect',
            rect: { x: 60, y: 100, width: 200, height: 48 },
            fill: 'brand.primary',
            borderRadius: 8,
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'operation-text',
            field: 'custom',
            rect: { x: 60, y: 100, width: 200, height: 48 },
            defaultText: 'EN VENTA',
            style: {
              fontFamily: 'Inter',
              color: '#FFFFFF',
              fontSize: 22,
              fontWeight: 'bold',
              textAlign: 'center',
              textTransform: 'uppercase',
              letterSpacing: 2,
            },
            zIndex: 3,
          },
          {
            type: 'text',
            id: 'title',
            field: 'title',
            rect: { x: 60, y: 1520, width: 960, height: 80 },
            style: {
              fontFamily: 'Inter',
              color: '#FFFFFF',
              fontSize: 48,
              fontWeight: 'bold',
              textAlign: 'left',
              lineHeight: 1.1,
              maxLines: 2,
            },
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'price',
            field: 'price',
            rect: { x: 60, y: 1620, width: 960, height: 70 },
            style: {
              fontFamily: 'Inter',
              color: 'brand.secondary',
              fontSize: 56,
              fontWeight: 'black',
              textAlign: 'left',
            },
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'location',
            field: 'location',
            rect: { x: 60, y: 1700, width: 600, height: 45 },
            style: {
              fontFamily: 'Inter',
              color: '#CCCCCC',
              fontSize: 30,
              fontWeight: 'normal',
              textAlign: 'left',
            },
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'features',
            field: 'features',
            rect: { x: 60, y: 1755, width: 700, height: 40 },
            style: {
              fontFamily: 'Inter',
              color: '#AAAAAA',
              fontSize: 26,
              fontWeight: 'normal',
              textAlign: 'left',
              maxLines: 1,
            },
            zIndex: 2,
          },
          {
            type: 'logo',
            id: 'logo',
            rect: { x: 860, y: 1760, width: 160, height: 100 },
            fit: 'contain',
            zIndex: 2,
          },
          {
            type: 'text',
            id: 'cta',
            field: 'cta',
            rect: { x: 60, y: 1830, width: 700, height: 40 },
            style: {
              fontFamily: 'Inter',
              color: 'brand.secondary',
              fontSize: 24,
              fontWeight: 'bold',
              textAlign: 'left',
            },
            zIndex: 2,
          },
        ],
      },
    ],
  },
};
